server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost/vlmart?useSSL=false
    username: root
    password: 123456aA@
    driverClassName: org.mariadb.jdbc.Driver
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update