server:
  port: 8080
  compression:
    enabled: true

spring:
  application:
    name: base-project

  main:
    banner-mode: off
    logStartupInfo: false
#    lazy-initialization: true

  # DATASOURCE
  datasource:
    url: jdbc:postgresql://128.199.140.126:5432/multikart
    username: postgres
    password: 123456aA@
    driverClassName: org.postgresql.Driver

  # JPA / HIBERNATE
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 100
      cache:
        use_second_level_cache: true
        use_query_cache: true

  session:
    storeType: redis # Session store type.
    redis:
      flush-mode: on_save # Sessions flush mode.
      namespace: spring:session # Namespace for keys used to store sessions.
      timeout: 480 # minutes

  # THYMELEAF
  thymeleaf:
    cache: true
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  cache:
    type: redis
    redis:
      timeToLive: 6000000

  redis:
    host: 128.199.140.126 # Redis server host.
    password: # Login password of the redis server.
    port: 16379 # Redis server port.
    ssl: false #enable SSL
    database: 0 # Redis database index.
    timeout: 5000

# LOGGING
logging:
  level:
    org:
      springframework:
        web: TRACE
        ws:
          client:
            MessageTracing:
              sent: TRACE
              received: TRACE
          server:
            MessageTracing:
              sent: TRACE
              received: TRACE
    root: INFO
    org.hibernate.SQL: INFO
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%X{X-B3-TraceId},%X{X-B3-SpanId},%X{X-B3-ParentSpanId},%X{X-Span-Export}] [${spring.application.name}] %-5level [%thread] %logger{50}.%M - %msg%n"
#  file:
#    name: logs/default.log