server:
  port: 8080

spring:
  application:
    name: base-project

  main:
    lazy-initialization: true

  # DATASOURCE
  datasource:
    url: jdbc:postgresql://128.199.140.126:5432/multikart
    username: root
    password: 123456aA@
    driverClassName: org.postgresql.Driver

  # JPA / HIBERNATE
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 100

  session:
    storeType: jdbc
    jdbc:
      initializeSchema: always
      tableName: spring_session

  # THYMELEAF
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

  mvc:
    hiddenmethod:
      filter:
        enabled: true

# LOGGING
logging:
  level:
    org:
      springframework:
        web: TRACE
        ws:
          client:
            MessageTracing:
              sent: TRACE
              received: TRACE
          server:
            MessageTracing:
              sent: TRACE
              received: TRACE
    root: INFO
    org.hibernate.SQL: INFO
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%X{X-B3-TraceId},%X{X-B3-SpanId},%X{X-B3-ParentSpanId},%X{X-Span-Export}] [${spring.application.name}] %-5level [%thread] %logger{50}.%M - %msg%n"
  file:
    name: logs/default.log