server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://pc.xdorro.dev:3306/multikart?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: 123456aA@
    driverClassName: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none