server:
  port: 8080

spring:
  application:
    name: base-project

  main:
    lazy-initialization: true

  # DATASOURCE
  datasource:
    url: jdbc:postgresql://128.199.140.126:5432/multikart
    username: root
    password: 123456aA@
    driverClassName: org.postgresql.Driver

  # JPA / HIBERNATE
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 100

  session:
    store-type: redis # Session store type.
    jdbc:
      initializeSchema: always
      tableName: spring_session
    redis:
      flush-mode: on_save # Sessions flush mode.
      namespace: spring:session # Namespace for keys used to store sessions.

  # THYMELEAF
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  redis:
    host: localhost # Redis server host.
    password: # Login password of the redis server.
    port: 6379 # Redis server port.

# LOGGING
logging:
  level:
    org:
      springframework:
        web: TRACE
        ws:
          client:
            MessageTracing:
              sent: TRACE
              received: TRACE
          server:
            MessageTracing:
              sent: TRACE
              received: TRACE
    root: INFO
    org.hibernate.SQL: INFO
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%X{X-B3-TraceId},%X{X-B3-SpanId},%X{X-B3-ParentSpanId},%X{X-Span-Export}] [${spring.application.name}] %-5level [%thread] %logger{50}.%M - %msg%n"
  file:
    name: logs/default.log